version: '2'
services:
  redis:
    image: redis:3-alpine
    restart: always
    ports:
      - "6379:6379"
    
  pg:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD
    ports:
      - "8888"
    restart: always
    
  nginx:
    image: karfai42/frontend:latest
    ports:
      - "80:80"
    links:
      - xa-lichen
      - xa-registry
      - xa-repository
    restart: always

  mongo:
    image: mongo:3.3
    restart: always

  xa-lichen:
    command: bundle exec puma
    depends_on:
      - pg
      - redis
    links:
      - pg
      - redis
    environment:
      - POSTGRES_HOST=pg
      - POSTGRES_PASSWORD
      - REDIS_URL=redis://redis:6379

  xa-lichen-worker:
    command: bundle exec sidekiq
    depends_on:
      - pg
      - redis
    links:
      - pg
      - redis
    environment:
      - POSTGRES_HOST=pg
      - POSTGRES_PASSWORD
      - REDIS_URL=redis://redis:6379
      
  xa-registry:
    command: bundle exec puma
    links:
      - mongo

  xa-repository:
    command: bundle exec puma
    links:
      - mongo
      
