version: '2'
services:
  pg:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD
    ports:
      - "8888"
    restart: always
    
  nginx:
    image: karfai42/frontend:latest
    ports:
      - "80:80"
    links:
      - xa-lichen
      - xa-registry
      - xa-repository
    restart: always

  mongo:
    image: mongo:3.3
    restart: always

  xa-lichen:
    command: bundle exec puma
    links:
      - pg
    environment:
      - POSTGRES_HOST=pg
      - POSTGRES_PASSWORD

  xa-registry:
    command: bundle exec puma
    links:
      - mongo

  xa-repository:
    command: bundle exec puma
    links:
      - mongo
      
